- name: Create a directory if it does not exist
  become: true
  file:
    path: "{{base_dir}}"
    state: directory
    
- name: Deploy dht script
  become: true
  copy: src=dht11.py dest="{{base_dir}}"

- name: Deploy dht
  become: true
  copy: src=dht.service dest=/etc/systemd/system/
  
- name: Deploy dht
  become: true
  template:
    src: dht.service
    dest: /etc/systemd/system/

- name: Start service
  become: true
  systemd: name=dht state=restarted enabled=yes
