- name: Create a directory if it does not exist
  become: true
  file:
    path: "{{base_dir}}"
    state: directory
    
- name: Deploy dht script
  become: true
  copy: src=dht11.py dest="{{base_dir}}"

- name: Deploy dht in
  become: true
  template:
    src: dht_in.service
    dest: /etc/systemd/system/

- name: Start service in
  become: true
  systemd: 
    name: dht_in
    daemon_reload: yes
    state: restarted 
    enabled: yes
    
    
- name: Deploy dht out
  become: true
  template:
    src: dht_out.service
    dest: /etc/systemd/system/

- name: Start service out
  become: true
  systemd: 
    name: dht_out
    daemon_reload: yes
    state: restarted 
    enabled: yes    
